# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'warsztaty.azurecr.io'
          repository: 'MinApi'
          command: 'buildAndPush'
          Dockerfile: 'src/MinApi/Dockerfile'
          buildContext: 'src/MinApi/'
      - task: replacetokens@5
        inputs:
          targetFiles: 'infra/*.yaml'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
      - upload: infra
        artifact: infra


  - stage: Production
    displayName: Deploy stage
    dependsOn: Build
    jobs:
    - deployment: Production
      environment: prod-k8s
      strategy:
       runOnce:
         deploy:
           steps:
           - task: KubernetesManifest@0
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: 'warsztaty-aks-eun-test'
               namespace: 'demo'
               manifests: '$(Pipeline.Workspace)/infra/*.yaml'