apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
      - name: Demo
        value: "To jest moja wartosc"
      - name: REF_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: REF_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
