apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  testowy_env: "Inna wartosc"
  demo_v2: "jest super"
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    envFrom:
      - configMapRef:
          name: my-config