apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources: {}
    volumeMounts:
      - mountPath: /app/
        name: config
    env:
      - name: demo_secret
        valueFrom:
# kubectl create secret generic kuard-config --from-literal=test=pracuj.pl --from-literal=test2="pracuj.pl jest super"
# tylko jak nie da sie inaczej
          secretKeyRef:
            key: test
            name: kuard-config
  volumes:
    - name: config
# zalecana
# kubectl create secret generic appsettings --from-file=appsettings.json -o yaml --dry-run=client | kubectl apply -f -
      secret:
        secretName: appsettings